### ISSUE TITLE
Running code with SpecialSetup.py

### ISSUE THREAD

**Issue by SeanPoints** [kslong/kred#32]

**Comment by SeanPoints** [comment]
Running commit version 5f2494dc442a2b906223d4bd45ae1b5313db2758
Have used special field that covers part of SMC_c03 and SMC_c06. The object file is:
[test.txt](https://github.com/user-attachments/files/17559953/test.txt)
and the overlap region can be see in the attached image
<img width="597" alt="Screenshot 2024-10-29 at 10 13 32 AM" src="https://github.com/user-attachments/assets/335e144c-76f0-4b42-a8d5-4bb742ec4a8e">

Everything runs fine through BackSub.py.

Try to run SwarpSetUp.py -bsub test smc_tst and get the following error:
(decam) spoints-ld1[88:workspace30] SwarpSetup.py -bsub test smc_tst

so the directory structure needed by swarp is not created.
[2024-10-29 13:16:37] Current commit: 5f2494dc442a2b906223d4bd45ae1b5313db2758
Traceback (most recent call last):
  File "/home/points/bin/kred/py_progs/SwarpSetup.py", line 547, in <module>
    steer(sys.argv)
  File "/home/points/bin/kred/py_progs/SwarpSetup.py", line 530, in steer
    create_commmands_for_one_tile(field,one,bsub=bsub,use_config=use_config)
  File "/home/points/bin/kred/py_progs/SwarpSetup.py", line 461, in create_commmands_for_one_tile
    xtab=summarize(field,tile)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/points/bin/kred/py_progs/SwarpSetup.py", line 89, in summarize
    header=x.meta['comments']
           ~~~~~~^^^^^^^^^^^^
KeyError: 'comments'

**Comment by kslong** [comment]
@SeanPoints   I may have messed up something when I fixed our standard processing so that it could get overlapping data, partly because Setuptile, can now do everything the SetupSpecial can do.  The problem is that Setup Tile adds some meta data to one of the output tables.  Please send me the complete set of commands you used.

**Comment by SeanPoints** [comment]
MefCheck.py SMC_c03
MefCheck.py SMC_c06
MefSum.py -np 8 SMC_c03
MefSum.py -np 8 SMC_c06
MefPrep.py -np 8 SMC_c03
MefPrep.py -np 8 SMC_c06
SetupSpecial.py -field SMC_c03 -field SMC_c06 /home/points/bin/kred/config/test.txt smc_tst
FindOverlaps.py test smc_tst
BackPrep.py -all -run test
BackStats.py  -np 8 -rm test smc_tst
BackCalc.py test smc_tst
BackSub.py -np 8 test smc_tst
SwarpSetup.py -bsub  test smc_tst
2024-10-29 13:16:37] Current commit: https://github.com/kslong/kred/commit/5f2494dc442a2b906223d4bd45ae1b5313db2758
Traceback (most recent call last):
File "/home/points/bin/kred/py_progs/SwarpSetup.py", line 547, in
steer(sys.argv)
File "/home/points/bin/kred/py_progs/SwarpSetup.py", line 530, in steer
create_commmands_for_one_tile(field,one,bsub=bsub,use_config=use_config)
File "/home/points/bin/kred/py_progs/SwarpSetup.py", line 461, in create_commmands_for_one_tile
xtab=summarize(field,tile)
^^^^^^^^^^^^^^^^^^^^^
File "/home/points/bin/kred/py_progs/SwarpSetup.py", line 89, in summarize
header=x.meta['comments']
~~~~~~^^^^^^^^^^^^
KeyError: 'comments'

**Comment by kslong** [comment]
Gracias @SeanPoints   I know what to do to fix this.  I/we just have to decide whether to keep SetupSpecial or to incorporate it's capabilities into SetupTile.  Right now the config file is a bit different.

**Comment by SeanPoints** [comment]
This is fine.  I need to try the other code update to see if I can use the classic version of the code that will pull in data from overlap regions between/among fields.  Say, run SMC_c03 T05 and see if that pull the data from SMC_c06 to fill out the missing parts.  I'll work on this tomorrow morning.

**Comment by kslong** [comment]
@SeanPoints  Please run your commands from the SetupSpecial command to see if I have addressed this issue.  If so, please close the issue.

As I suspected, what I had not done is written some meta data for the center (RA, and Dec)  of the image to the Summary file that says what images to include in making a final image.  As fixed, the output images should now be centered on the desired position.
