### ISSUE TITLE
Failure in PrepSum when fields do not have N708 observations

### ISSUE THREAD

**Issue by SeanPoints** [kslong/kred#9]
PrepSum.py gave an error on LMC_c36 because there are no N708 observations associated with the field. 
---
N708
Traceback (most recent call last):
  File "/home/points/data/DECam/LMC/kred/py_progs/PrepSum.py", line 342, in <module>
    steer(sys.argv)
  File "/home/points/data/DECam/LMC/kred/py_progs/PrepSum.py", line 326, in steer
    do_all_tiles(field)
  File "/home/points/data/DECam/LMC/kred/py_progs/PrepSum.py", line 190, in do_all_tiles
    do_one_tile(field,tile='T%02d' % i)
  File "/home/points/data/DECam/LMC/kred/py_progs/PrepSum.py", line 179, in do_one_tile
    overview(field,tile)
  File "/home/points/data/DECam/LMC/kred/py_progs/PrepSum.py", line 282, in overview
    xtab['Filter']='N708'
  File "/home/points/anaconda/envs/npy37/lib/python3.7/site-packages/astropy/table/table.py", line 1899, in __setitem__
    self.add_column(value, name=item, copy=True)
  File "/home/points/anaconda/envs/npy37/lib/python3.7/site-packages/astropy/table/table.py", line 2168, in add_column
    raise TypeError('Empty table cannot have column set to scalar value')
---
Seems like software expects that all fields have N708 images and fails when there are not any.

I've made a temporary workaround by copying PrepSum.py to PrepSum_sdp.py and deleting the code that references N708 filter.  There is probably a more elegant way to handle this. My modified version is working and field LMC_c36 has completed PrepSum_sdp.py with N708 removed from processing steps.

**Comment by kslong** [comment]
This particularly error may be moot, as PrepSum is being removed from the reduction pipeline.

**Comment by kslong** [comment]
I have checked that with the new version of the S/W does not breakdown on LMC_c36, so I am closing this issue.
